### ISSUE TITLE
[1.7.10] Incompatibility with FastCraft

### ISSUE THREAD

**Issue by HRudy94** [Team-Fruit/Emojicord#18]
## Environment
- Minecraft 1.7.10
- Forge 1614
- EmojiCord 1.0.2.15
- FastCraft 1.25

## To Reproduce
1. Launch the game with both FastCraft and EmojiCord
2. Open the chat
3. You will see that the emojis are replaced by white text.

## Expected behavior
Emojis should render correctly.

## Actual behavior
Emojis are rendered by their names in white text, making the menu not display anything and the emojis just showing like their usualnames.

**Comment by Kamesuta** [comment]
Fixed in Emojicord v1.1.1
